### ISSUE TITLE
I could add kents c ddos method of testing? using mock server if its ok ? guy behind test-library 

### ISSUE THREAD

**Issue by stephyswe** [zero-to-mastery/breads-client#56]

**Comment by aTmb405** [comment]
Yes, go for it! I'll add it to the client tests task on Trello (see link in discord channel)

**Comment by aTmb405** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update client tests](https://trello.com/c/hJ9tDpxI/2-update-client-tests)

**Comment by aTmb405** [comment]
@stephyswe How is this issue going? Have you been able to make much progress?

**Comment by stephyswe** [comment]
> @stephyswe How is this issue going? Have you been able to make much progress?

with what?

**Comment by stephyswe** [comment]
> @stephyswe How is this issue going? Have you been able to make much progress?

@aTmb405 Oh yeah. Well it's good i waited. I learned so much the last month. I will make sure you have a really solid testing system this week : )

**Comment by aTmb405** [comment]
@stephyswe Awesome, thanks!
