### ISSUE TITLE
Sign Up page glitched

### ISSUE THREAD

**Issue by milan090** [zero-to-mastery/breads-client#61]
## Bug Report
![image](https://user-images.githubusercontent.com/56679289/110266303-62e64b80-7fb5-11eb-9402-c12d2e58b7ad.png)

Using:
- Arch Linux
- Chrome stable Version 89.0.4389.72 (Official Build) (64-bit)

**Comment by aTmb405** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sign Up form labels and textboxes are not at right position](https://trello.com/c/zVIDcaf5/47-sign-up-form-labels-and-textboxes-are-not-at-right-position)

**Comment by aTmb405** [comment]
Thanks! I've linked it to a Trello card

**Comment by jalajcodes** [comment]
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Sign Up form labels and textboxes are not at right position](https://trello.com/c/zVIDcaf5/47-sign-up-form-labels-and-textboxes-are-not-at-right-position)

this link is not working

**Comment by aTmb405** [comment]
> > ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Sign Up form labels and textboxes are not at right position](https://trello.com/c/zVIDcaf5/47-sign-up-form-labels-and-textboxes-are-not-at-right-position)
> 
> this link is not working

@jalajcodes sign up for the [Trello board](https://trello.com/invite/b/QIgGHAqu/645ae6a5b26add1b528fd520dc105e3b/breadsio) for it to work. We are working on integrating GitHub and Trello better

**Comment by jalajcodes** [comment]
> > > ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Sign Up form labels and textboxes are not at right position](https://trello.com/c/zVIDcaf5/47-sign-up-form-labels-and-textboxes-are-not-at-right-position)
> > 
> > this link is not working
> 
> @jalajcodes sign up for the [Trello board](https://trello.com/invite/b/QIgGHAqu/645ae6a5b26add1b528fd520dc105e3b/breadsio) for it to work. We are working on integrating GitHub and Trello better

Oh okay!

btw GitHub has project boards for every repo, why not just use that?

**Comment by aTmb405** [comment]
ZTM provided the trello board, which is nice. I think we can also control who has access to the project board more easily if the access should need to change in the future.
