### ISSUE TITLE
Submitting article with empty fields results in "saved article"

### ISSUE THREAD

**Issue by cabralh** [zero-to-mastery/breads-client#66]
When the user clicks on the plus button to submit an article with empty fields, the website tries to save it.

![image](https://user-images.githubusercontent.com/69700431/111052525-75cfa480-8429-11eb-80b9-c9186fbdb713.png)

**Comment by aTmb405** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Submitting article with empty fields results in "saved article"](https://trello.com/c/rGtWPyoT/51-submitting-article-with-empty-fields-results-in-saved-article)
