### ISSUE TITLE
Transition to TypeScript

### ISSUE THREAD

**Issue by aubundy** [zero-to-mastery/breads-client#71]
Most of the client side code is in TypeScript, but a few more files need to be transitioned

- [x] `src/features/subscriptions`
- [x] `src/features/tags`
- [x] `src/features/tagsList`
- [x] `src/features/user`

**Comment by aTmb405** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transition to TypeScript](https://trello.com/c/tbyjexZu/9-transition-to-typescript)
