### ISSUE TITLE
Article Form on Mobile

### ISSUE THREAD

**Issue by aTmb405** [zero-to-mastery/breads-client#75]
The upload article form displays at the top of the page on mobile. It would be nice for this to become a floating button in the bottom right corner when a user is on mobile

**Comment by aTmb405** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move article form on mobile](https://trello.com/c/qqBBKvaN/22-move-article-form-on-mobile)

**Comment by JorgePasco1** [comment]
I'd like to work on this!

**Comment by aTmb405** [comment]
@JorgePasco1 Awesome! I'll assign it to you now. Feel free to reach out with any questions

**Comment by JorgePasco1** [comment]
@aTmb405 I cannot access the Trello Card ⬆️. Does it have any relevant information?
![image](https://user-images.githubusercontent.com/25943796/121790959-70a9ff00-cbaa-11eb-951c-1a8814dc6c64.png)

**Comment by aTmb405** [comment]
@JorgePasco1 It does not. It has the same instructions as this issue, I'm just (slowly) moving all Trello cards to GitHub issues

**Comment by aTmb405** [comment]
@JorgePasco1 Thanks again for fixing this. If you want to see a fuller list of issues, you can join the [breads discord group](https://discord.com/channels/423464391791476747/590543741660692487) and the pinned messages have links to Trello
